#+title: Notes
#+author: Alfredo Mejia
#+options: num:nil html-postamble:nil
#+html_head: <link rel="stylesheet" type="text/css" href="./resources/bulma/bulma.css" /> <style>body {margin: 5%} h1,h2,h3,h4,h5,h6 {margin-top: 3%}</style>

* Welcome
Welcome to my repository called notes. This repo will have notes about anything I wish to take notes on. This can be a YouTube video, a course, a book, a process, like how to wash a car properly, research papers, articles, technologies, etc. Many of the times, when I take down notes on whatever it may be, I either delete the files, throw out the paper, or simply take down bad notes.

I want to start something different. I want to build my "second brain", my garden of knowledge, or whatever you may call it. I've tried before. I've tried to build this "second brain" either by using OneNote, Notion, Obsidian, MediaWiki, or Confluence. However, each time, I overcomplicate it. I've spent countless hours researching the best workflow for taking down notes. I've tried to build folders for different categories, then subfolders for different subcategories, tried to interconnect my notes with each other, and I've tried to add tags to my notes. I realized, that was a waste of time because none of that seemed to work for me. In the end, I was left exhausted and without good notes.

Now, I'm going to take a different approach. For one, each book, course, video, article, research paper, whatever it may be, will have its own folder in the root directory. This would avoid having so many nested folders to eventually get to the notes of interest. Second, I'm going to try and keep it simple. I will take down notes in plain text using Org-Mode in Emacs. Hopefully this new process works for me and hopefully I don't get stuck in this cycle where I am changing my process once more to take down notes.

* What will each folder have?
The goal is for each folder to correspond to a course, book, research paper, article, video, etc. If the video / book is long there may be folders or multiple files to separate the topics / chapters. However, I am not just going to take down notes. Notes are great but you need to do more to fully understand the material. So, in addition to notes, I am going to try to create how-to-wikis, projects, answer textbook questions, and more. Each folder will be more than just notes.

In addition, each folder will have an org-file and a HTML file. The org-file would be used to store the notes but the great thing about Org-Mode in Emacs is that you can create internal links and navigate between files. Emacs also have a great HTML export option which I will be using. Thus we will have two files per note: an org-file and a HTML file.

The HTML file will use the default export options of Emacs but the only difference is that I will be using [[https://bulma.io][Bulma]] CSS to simply style my headings, paragraphs, etc. I will simply attach the Bulma's CSS file to the HTML file. Other than that no changes will be made to the HTML file.

* What Next
Please feel free to enter any folder, explore my projects and use my notes. Most projects will be small and thus will not have its own repo, but who knows, in the future a project may be expanded and have its own dedicated repo.

Depending on how you are navigating my notes (html, org, or Github) you can click on the internal links below to explore my notes.

* Folders
| Title                                                            | Author                        | HTML | ORG | GitHub | Status      |
|------------------------------------------------------------------+-------------------------------+------+-----+--------+-------------|
| College Algebra                                                  | Ron Larson & Robert Hostetler | [[file:./College_Algebra/000.Home.html][html]] | [[file:./College_Algebra/000.Home.org][org]] | [[https://github.com/alfredo-mejia/notes/tree/main/College_Algebra][github]] | Archived    |
| HTML & CSS - Design and Build Websites                           | Jon Duckett                   | [[file:./HTML_and_CSS_Design_and_Build_Websites/000.Home.html][html]] | [[file:./HTML_and_CSS_Design_and_Build_Websites/000.Home.org][org]] | [[https://github.com/alfredo-mejia/notes/tree/main/HTML_and_CSS_Design_and_Build_Websites][github]] | Completed   |
| Introduction to Oracle Cloud Essentials                          | [[https://mylearn.oracle.com/ou/home][Oracle University]]             | [[file:./Introduction_to_Oracle_Cloud_Essentials/000.Home.html][html]] | [[file:./Introduction_to_Oracle_Cloud_Essentials/000.Home.org][org]] | [[https://github.com/alfredo-mejia/notes/tree/main/Introduction_to_Oracle_Cloud_Essentials][github]] | In-Progress |
| JavaScript & JQuery - Interactive Front-End Web Development      | Jon Duckett                   | [[file:./JavaScript_and_JQuery_Interactive_Frontend_Web_Development/000.Home.html][html]] | [[file:./JavaScript_and_JQuery_Interactive_Frontend_Web_Development/000.Home.org][org]] | [[https://github.com/alfredo-mejia/notes/tree/main/JavaScript_and_JQuery_Interactive_Frontend_Web_Development][github]] | In-Progress |
| The Complete 2024 Web Development Bootcamp                       | Dr. Angela Yu                 | [[file:./The_Complete_2024_Web_Development_Bootcamp/000.Home.html][html]] | [[file:./The_Complete_2024_Web_Development_Bootcamp/000.Home.org][org]] | [[https://github.com/alfredo-mejia/notes/tree/main/The_Complete_2024_Web_Development_Bootcamp][github]] | Archived    |
| The Web Developer Bootcamp 2024                                  | Colt Steele                   | [[file:./The_Web_Developer_Bootcamp_2024/000.Home.html][html]] | [[file:./The_Web_Developer_Bootcamp_2024/000.Home.org][org]] | [[https://github.com/alfredo-mejia/notes/tree/main/The_Web_Developer_Bootcamp_2024][github]] | Archived    |
| User's Guide for Oracle Business Intelligence Enterprise Edition | [[https://docs.oracle.com/][Oracle Docs]]                   | [[file:./Users_Guide_for_Oracle_Business_Intelligence_Enterprise_Edition/000.Home.html][html]] | [[file:./Users_Guide_for_Oracle_Business_Intelligence_Enterprise_Edition/000.Home.org][org]] | [[https://github.com/alfredo-mejia/notes/tree/main/Users_Guide_for_Oracle_Business_Intelligence_Enterprise_Edition][github]] | Archived    |

