# Generated by Django 4.2.22 on 2025-06-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_url',
            field=models.URLField(default=''),
        ),
    ]
